services:
  ipa-server:
    image: quay.io/freeipa/freeipa-server:rocky-9-4.12.2
    container_name: ipa-server
    hostname: server.ipa.local
    networks:
      - slurm-network
    environment:
      - PASSWORD=password
    volumes:
      - ./ipa-data:/data:Z
    read_only: true
    restart: unless-stopped
    command: >
      ipa-server-install
      -r IPA.LOCAL
      --no-ntp
      --unattended

  mysql:
    image: docker.io/mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurmdbd/${IMAGE_TAG}
    build:
      context: .
      target: slurmdbd
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: slurmctld:${IMAGE_TAG}
    build:
      context: .
      target: slurmctld
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld.ipa.local
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
      - "ipa-server"
    networks:
      - slurm-network

  c1:
    image: slurmd:${IMAGE_TAG}
    build:
      context: .
      target: slurmd
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmd"]
    hostname: c1.ipa.local
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
      - "ipa-server"
    networks:
      - slurm-network

  c2:
    image: slurmd:${IMAGE_TAG}
    command: ["slurmd"]
    hostname: c2.ipa.local
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
      - "ipa-server"
    networks:
      - slurm-network

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
